apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: metal-ip
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      name: https
      port: 5050
      targetPort: 5050
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deploy
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress_image
        imagePullPolicy: Never
        ports:
        - containerPort: 5050