apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: metal-ip
spec:
  selector:
    app: ftps
  ports:
  - port: 21
    targetPort: 21
    name: ftp21
  - port: 20
    targetPort: 20
    name: ftp20
  - port: 30020
    targetPort: 30020
    name: ftp30020
  - port: 30021
    targetPort: 30021
    name: ftp30021
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deploy
spec:
  selector:
    matchLabels:
      app: ftps
  replicas: 1
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_image
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 20
        - containerPort: 30020
        - containerPort: 30021