apiVersion: v1
kind: Service
metadata:
  name: pma
  annotations:
    metallb.universe.tf/allow-shared-ip: metal-ip
spec:
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma-deploy
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: pma_image
        imagePullPolicy: Never
        ports:
        - containerPort: 5000